# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  config.vm.define "nginx-server" do |vm1|
    vm1.vm.hostname = "nginx-server"
    vm1.vm.box = "centos/7"
    vm1.vm.box_version = "1905.1"
    vm1.hostmanager.enabled = true
    vm1.hostmanager.manage_host = true
    vm1.hostmanager.manage_guest = true
    vm1.hostmanager.ignore_private_ip = false
    vm1.hostmanager.include_offline = true
    vm1.vm.network "private_network", ip: "192.168.33.30"
    vm1.vm.network "forwarded_port", guest: 80, host: 8888
    vm1.vm.provision "shell", path: "./provision/nginx.sh"
    vm1.vm.synced_folder "./nginx_share","/home/vagrant/shared_folder",type:"virtualbox"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "nginx-server1"
      vb.gui = false
      vb.memory = 1024
      vb.cpus = 2
    end
  end  
  config.vm.define "ConfluenceVM" do |vm1|
    vm1.hostmanager.enabled = true
    vm1.hostmanager.manage_host = true
    vm1.hostmanager.manage_guest = true
    vm1.hostmanager.ignore_private_ip = false
    vm1.hostmanager.include_offline = true
    vm1.vm.hostname = "confluenceVM"
    vm1.vm.box = "generic/ubuntu1804" 
    vm1.vm.provision "shell", path: "./provision/mount.sh"
    vm1.vm.provision "shell", path: "./provision/increase_swap.sh"
    vm1.vm.provision "shell", path: "./provision/conf.sh"
    vm1.vm.network "private_network", ip: "192.168.33.10"
    vm1.vm.network "forwarded_port", guest: 8090, host: 8090
    vm1.vm.synced_folder "./conf_share","/home/vagrant/shared_folder",type:"virtualbox"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "confl-ubuntu1"
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 2
      (1..2).each do |i|
        unless File.exist?("mydisk#{i}.vmdk")
          if i == 1 then
            vb.customize ['storagectl', :id, '--name', 'mySATA Controller', '--add', 'sata', '--portcount',4]
            end
	  vb.customize [ "createmedium", "disk", "--filename","mydisk#{i}.vmdk", "--format", "vmdk", "--size", 5000 ]
        end
        vb.customize [ "storageattach", :id , "--storagectl", "mySATA Controller", "--port", "#{i}", "--device", "0", "--type", "hdd", "--medium","mydisk#{i}.vmdk"]
      end
    end
  end
  config.vm.define "MySql" do |vm2|
    vm2.hostmanager.enabled = true
    vm2.hostmanager.manage_host = true
    vm2.hostmanager.manage_guest = true
    vm2.hostmanager.ignore_private_ip = false
    vm2.hostmanager.include_offline = true
    vm2.vm.hostname = "mysqlserver"
    vm2.vm.box = "ubuntu/bionic64"
    vm2.vm.provision "shell", path: "./provision/mount.sh"
    vm2.vm.provision "shell", path: "./provision/mysql.sh"
    vm2.vm.network "private_network", ip: "192.168.33.20"
    vm2.vm.network "forwarded_port", guest: 3306, host: 3306
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "mysql-ubuntu1"
      vb.gui = false
      vb.memory = 2048
      vb.cpus = 2
      (1..2).each do |i|
	 if i == 1 then
            vb.customize ['storagectl', :id, '--name', 'mySATA Controller', '--add', 'sata', '--portcount',4]
         end
        unless File.exist?("mydisk#{i}.vmdk")
          vb.customize [ "createmedium", "disk", "--filename","mydisk#{i}.vmdk", "--format", "vmdk", "--size", 2000 ]
        end
        vb.customize [ "storageattach", :id , "--storagectl", "mySATA Controller", "--port", "#{i}", "--device", "0", "--type", "hdd", "--medium","mydisk#{i}.vmdk"]
      end
    end
  end

  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end

